version: '3'

networks: 
  kafka:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks:
      - kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    networks:
      - kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
 
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    networks: 
      - kafka
    depends_on:
      - broker
    ports:
      - 8088:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092

  database:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  openapi:
    image: redocly/redoc:v2.0.0
    container_name: openapi
    restart: always
    environment:
      SPEC_URL: openapi-docs.json
      REDOC_OPTIONS: "sort-tags-alphabetically path-in-middle-panel required-props-first side-nav-style='path-only'"
    ports:
      - 8080:80
    volumes:
      - ./apps/api-gateway/docs/openapi/openapi-docs.json:/usr/share/nginx/html/openapi-docs.json:ro
